tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

brew cask install "1password"
brew cask install "adobe-creative-cloud"
brew cask install "autodesk-fusion360"
brew cask install "balenaetcher"
brew cask install "bfxr"
brew cask install "blender"
brew cask install "brave-browser"
brew cask install "cyberduck"
brew cask install "discord"
brew cask install "fontforge"
brew cask install "github"
brew cask install "gog-galaxy"
brew cask install "google-backup-and-sync"
brew cask install "google-drive-file-stream"
brew cask install "iterm2"
brew cask install "kindle"
brew cask install "licecap"
brew cask install "microsoft-teams"
brew cask install "onedrive"
brew cask install "origami-studio"
brew cask install "pritunl"
brew cask install "processing"
brew cask install "qlcolorcode"
brew cask install "qlimagesize"
brew cask install "qlmarkdown"
brew cask install "qlstephen"
brew cask install "qlvideo"
brew cask install "quicklook-json"
brew cask install "quicklookase"
brew cask install "rectangle"
brew cask install "sketch"
brew cask install "sketchbook"
brew cask install "slack"
brew cask install "steam"
brew cask install "teamviewer"
brew cask install "ultimaker-cura"
brew cask install "visual-studio-code"
brew cask install "vlc"
brew cask install "webpquicklook"
brew install "giflib"
brew install "git-lfs"
brew install "node", link: false
brew install "openssl@1.1"
brew install "pwgen"
brew install "rbenv"
brew install "ruby", link: true
brew install "wget"